### ISSUE TITLE
Impedido por proteção Captcha. Comportamento de Robô

### ISSUE THREAD

**Issue by guilhermebene** [engmsilva/scraping-das-mei#1]
Estava testando o projeto no local e aparentemente não está funcionando por aqui.
Quando rodo no modo headless obtenho um erro de timeout, mas rodando no modo interativo, depois de inserir o CNPJ e clical para proceder, aparece uma mensagem toast "13896 - Impedido por proteção Captcha. Comportamento de Robô.".
Aparentemente o sistema deve ter aumentado a segurança. Ou estou fazendo algo errado?

**Comment by johnbh3** [comment]
Continua mesmo bo?
Eita

Que chato
Tava usando 
Browserless e tenho em 2026 mesmo erro kkk triste heim kkk
